# Site settings
title: "AI CODE GEEK"
description: "🤖 AI Code Geek, Where AI meet code • Learn 📚 • Build ⚡ • Inspire 🚀"
author: "AI Code Geek Team"
email: "meera.success@gmail.com"
baseurl: ""
url: "https://aicodegeek.com"
# Build settings
markdown: kramdown
highlighter: rouge
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 3
paginate_path: "/page:num/"

# Theme settings
theme_color: "purple" # purple, cyan, orange, green
show_excerpts: true
posts_per_page: 5

# Collections
collections:
  posts:
    output: true
    #permalink: /:categories/:year/:month/:day/:title/
    permalink: /:year/:month/:day/:title

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Social links
social:
  github: "aicodegeek"
  twitter: "aicodegeek"
  linkedin: "aicodegeek"

# Navigation - Header pages (these will appear in the main navigation)
# List the actual file paths relative to the site root
header_pages:
  - "pages/about.md"
  - "pages/categories.html"
  - "pages/tags.html"
  - "pages/archive.html"
  - "pages/privacy.md"
  - "pages/contact.md"

# Site page definitions (for reference and metadata)
pages:
  # Main navigation pages
  about:
    title: "About"
    description: "Learn more about aicodegeek and our mission"
    permalink: "/about/"
    layout: "page"
    show_in_nav: true
    order: 1
  # Content organization pages
  categories:
    title: "Categories"
    description: "Browse posts by category"
    show_in_nav: true
    order: 2
  archive:
    title: "archive"
    description: "Browse all archive"
    permalink: "/archive/"
    layout: "page"
    show_in_nav: false
  tags:
    title: "Tags"
    description: "Browse all tags"
    permalink: "/tags/"
    layout: "page"
    show_in_nav: false
  # Legal pages
#  privacy:
#    title: "Privacy"
#    description: "Our privacy policy and data protection practices"
#    permalink: "/privacy/"
#    layout: "page"
#    show_in_nav: false
  contact:
    title: "Contact Us"
    description: "Contact Us"
    permalink: "/contact/"
    layout: "page"
    show_in_nav: true
    show_in_footer: true
  terms:
    title: "Terms of Service"
    description: "Terms and conditions for using our site"
    permalink: "/terms/"
    layout: "page"
    show_in_nav: false
    show_in_footer: true
# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/
  - robots.txt
  - README.md

# Sass settings
sass:
  style: compressed
  sass_dir: _sass

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
